### ISSUE TITLE
[DISCUSSION] stats rework

### ISSUE THREAD

**Issue by misterdev** [misterdev/webpack-reporter-plugin#1]
Stats actually contains a lot of information, the idea is to keep only metrics or aggregated values, and removed other stuff like single instance prints.

From this analysis, it seems that most of the stats don't belong to them, any comment is welcome!

KEEP IN STATS
- timings
- assets (with size)
- modules (with size)

SINGLE INSTANCE
- builtAt
- hash
- version

NOT METRIC INFO
- performance, show performance hint when file size exceeds `performance.maxAssetSize`
- publicPath, add public path information
- chunkGroups, add namedChunkGroups information
- providedExports, show the exports of the modules (this
- usedExports, show which exports of a module are used
- source, add the source code of modules
- chunks (chunkModules, chunkOrigins), info about chunks

STILL NOT SURE
- cached
- cachedAssets
- children, add children information

cc @evenstensberg @hulkish

**Comment by evenstensberg** [comment]
Could you elaborate on what you mean by single instance, keep in stats and such? There's many ways to include a reportig capability in webpack

**Comment by hulkish** [comment]
I think we should also consider maybe there are cases where we might actually want both stats + live report for cases where an explicit report of the final result is clear... 

Like for local dev u might prefer that. I guess I'm just saying we don't necessarily have a reason to force it to be only one

**Comment by misterdev** [comment]
(I've slightly updated the previous message)

From what I understand, we want to emit some of the data that are currently in stats separately from stats for the purpose of live reporting. How I imagine it is:
- `reporter.hook. stats`, will simply emit stats
- `reporter.hook.info`, will emit all the chosen compilation/compiler hooks + some of the information from stats

What is currently in stats that we should emit separately?
- Single Instance prompt (stuff outputted once) that are not aggregated metrics, (i.e. buildAt, hash & version)
- Non-Metric Data, that are information that do not contain metric information (e.g. performance hint, & chunkGroups information)

I've included a description of what I've understood because I'm still trying to get into your perspective, so I'm not 100% sure of every detail (actually, I can see some inconsistencies in my analysis)

**Comment by hulkish** [comment]
Hmm, actually... through live reporting it could be said stats functionality could be met. So, disregard my previous message.

**Comment by evenstensberg** [comment]
Maybe supporting as much as possible, but with the ability to filter noisy data like assets (which is huge, sometimes not needed) is a good starting point

**Comment by misterdev** [comment]
How should it be different from switching off assets directly from the "[stats](https://webpack.js.org/configuration/stats/#root)" configuration?

**webpack.config.js**

```js
module.exports = {
  //..
  stats: {
     // ...
    assets: false,
  }
};
```

**Comment by evenstensberg** [comment]
I don't think that is should be any different. Use that option

**Comment by misterdev** [comment]
Ok, good! So I'm not sure I'm getting the point, sorry 🙏🙏

The Ouput Reporter now has a "stats" [hook ](https://github.com/misterdev/webpack-reporter-plugin/blob/master/src/index.js#L120 )emitting stats, that are [printed ](https://github.com/misterdev/webpack-reporter-plugin/blob/master/src/reporter.js#L23) by the reporter according to the "[stats](https://webpack.js.org/configuration/stats/#root)" options in `webpack.config.js`.

From my understanding:
- the Output Reporter, should just emit the stats
- the Custom Reporter, should print stats how the user expects (aka according to what specified in `webpack.config.js`)
- "stats" can be customized in `webpack.config.js` allowing to select/deselect everything (assets, module, timings, ...)

If this is correct, I think there's nothing to do on this 

Maybe, what we want is to have some information like "buildAt" & "version" emitted by the OutputReporter "info" hook?

**Comment by hulkish** [comment]
@misterdev I think the answer to those questions lives somewhere in between best perf and best vision moving forward. I think we should reserve that focus for once this current effort is in place & stable, then re-evaluate what should occur for stats.
