### ISSUE TITLE
rfc: remove chalk & maybe also console.log

### ISSUE THREAD

**Issue by hulkish** [misterdev/webpack-reporter-plugin#4]
The actual `console.log` can just be left to the consumer of this npm package to implement - in this instance, that would be `webpack-cli`. 

Specifically, I'm referring to: https://github.com/misterdev/webpack-reporter-plugin/blob/master/src/reporter.js#L48-L54

I believe another solution may be to move `reporter.js` to `webpack-cli`. This makes much more sense to me. Or, even a separate plugin perhaps. What do you think @evenstensberg?

Or, we default to bare minimum (no chalk) .- but, allow user to override.

**Comment by misterdev** [comment]
Thanks for the feedback :)

`chalk` is meant to be a temporary solution to have colored output, I tried using ansi escape codes to avoid having chalk as dependency but eslint had some complains. I agree with you, it will be removed 👍

The idea is to have `reporter.js` as default reporter, it should be a fallback in case no reporters are specified in the config, eg:
```js
// webpack.config.js
{
    plugins: [
        new ReporterPlugin({
            reporters: []
        })
    ]
}
```
for this reason I think it should be in this repo or, as you suggest, in a separate plugin.

**Comment by hulkish** [comment]
@misterdev Honestly, I think we should be thinking more in terms of "how do we design this in a way so that only the user would need to install chalk?

**Comment by misterdev** [comment]
Yeah, I'll remove it. I just added temporarily to have a colored output while developing :) 

![1LknNHlchzk1mHbxoeQSMEmSRi-5C9Y7KNy66DoM](https://user-images.githubusercontent.com/11232797/59207225-f3a4b300-8ba6-11e9-8821-83c943776d71.png)

**Comment by evenstensberg** [comment]
I think removing chalk is a good way to go, less deps. Even though, we're using stats in webpack so it won't be a dependency problem it just looks bad

**Comment by misterdev** [comment]
It has been removed ([commit](https://github.com/misterdev/webpack-reporter-plugin/commit/51529b879dbef0e26d2ed024d9a489f2ba5941dc)) :) 

What do you think about where the default reporter should be? It is currently `src/reporter.js` @evenstensberg

**Comment by evenstensberg** [comment]
Sounds ok
